<x-guest-layout>
    <x-slot name="title">Nossa História</x-slot>
    <div class="header-session"><h1>SOBRE A IGREJA</h1></div>
    <section class="page page-history">
        <article class="container">
            <h1>Primeira Igreja Batista do Ingá</h1>
            <h2>Desde 1964 alcançando vidas</h2>
            <p>A Primeira igreja Batista do Ingá nasce no dia 10 de novembro de 1964. Nasce sob o signo e emblema da ousadia e coragem da Igreja de Cristo. Naquele momento da nossa história a Igreja Batista no Brasil vivia o contexto da <em>1ª Campanha Nacional de Evangelização</em>. Os corações estavam abrasados com o desejo sincero e ardente de que um verdadeiro e genuíno avivamento acontecesse na igreja e que a pátria brasileira fosse ganha para Cristo. Os Batistas Brasileiros viviam um momento singular de alegria e crescimento não apenas numérico, mas, em diversas áreas de seu ministério.</p>
            <p>O Pr. Samuel de Souza foi o instrumento usado por Deus para o surgimento da igreja. Ele era, então, diretor do Colégio Batista de Niterói e também Secretário Geral da <strong>ANEB (Associação Nacional de Educandários Batistas)</strong>. Numa das reuniões de planejamento da Campanha Nacional de Evangelização, como secretário da ANEB, fez uma proposta para que cada Colégio Batista no Brasil organizasse uma Congregação dentro de suas instalações.</p>
            <p>O Colégio Batista de Niterói, sob a liderança do Pr. Samuel, vai além, salta a etapa de <em>“Congregação”</em> e, reune um grupo de 31 irmãos oriundos de diversas igrejas, boa parte estudantes ligados à Casa do Estudante Batista que os acolhia e hospedava no período de estudos em Niterói.</p>
            <p>Então, sob os auspícios da Igreja Batista de Pendotiba e Igreja Batista de Icaraí promovem o concílio para a organização da Igreja Batista do Ingá, tendo como seus membros fundadores, os seguintes irmãos: <em>Pr. Samuel de Souza, Eva de Souza, Albino Dutra, Helena de Souza Tôrres, Joel Coelho dos Santos, Emma Ribeiro Capella, Diomar Maciel de Macedo, Humberto Silva de Macedo, Delíria Maciel Lopes Bretas, Francisca Maria Ramos Sias, Rosalee Ramos Sias, Newton de Souza, Delfina de Jesus, Agnaldo de Souza, Adair Santana de Oliveira dos Santos, Calinério Tôrres Braga, Denise Carvalho Souza, Silene de Carvalho Souza, Silas Ramos Sias, Joseir Reis de Faria</em>.</p>
            <p>Ao longo do seu primeiro ano de atividades a igreja recebeu em seu ról de membros, os seguintes irmãos: <em>Celeste Carvalho de Souza, Maria Amália Carvalho de Souza, Nicéia de Souza, Paulo da Rocha Sias, Lomar Ramos Sias, Vicente Ferreira dos Santos, Maria Simoná Bretas, Camilo Maciel Bretas, Elza Prado de Souza, Carlos Henrique Prado de Souza e Emiron de Andrade Martins Filho</em>, os quais temos denominado, informalmente, como Membros Pioneiros, pela importante participação na gênese desta igreja.</p>
            <p>A aquisição do terreno e a construção do templo atual foram dois importantes marcos nessa história de fé da Primeira Igreja Batista do Ingá. A igreja já havia adquirido o terreno de número 125, da rua Dr. Paulo Alves. Mais tarde, porém, quando estavam se preparando para iniciar a construção do novo templo, o Pr. Samuel de Souza, movido pelo Espírito Santo de Deus, inspirado pela Palavra do Senhor em Josué 1:3, que diz: <em>“Todo o lugar que pisar a planta do vosso pé, vo-lo tenho dado...”</em>, decidiu visitar o terreno, de número 121, ao lado da igreja.</p>
            <p>Nesse terreno seria construido um edificio de apartamentos e já estavam todos vendidos. Ainda assim, o Pr. Samuel pede ao vigia do terreno que lhe permita orar naquele lugar e fala da promessa bíblica. Dada a permissão ele entra, coloca alí a planta de seus pés e ora ao Senhor. De fato, algum tempo depois, o dono daquele terreno procurou o pastor e informou que havia desistido da obra, indenizado os compradores dos apartamentos e gostaria de dar à igreja a preferência para a aquisição do terreno.</p>
            <p>A igreja sob a liderança do Pr. Samuel inicia, então, uma grande campanha, levanta os recursos necessários e compra o terreno. Agora estavam diante de um desafio ainda maior. Mais um teste de fé na vida da igreja. Mais uma vez também, Deus usou o Pr. Samuel de Souza, dando-lhe sabedoria para administrar a campanha na igreja e toda esta grande obra. O Senhor colocou ao seu lado pessoas estratégicas para que a obra pudesse ser levada a efeito, dentre elas: sua filha Celeste Carvalho de Souza, arquiteta, que trabalhou na elaboração do projeto do templo e o irmão Jadson Gabriel Coelho Dias, gerente do Banco Econômico, que providenciou que a igreja recebesse por empréstimo os recursos necessários à obra. Ambos eram membros da igreja.</p>
            <p>Em 1982 o templo foi inaugurado ainda semi-pronto, para o casamento da irmã Celeste. Desse modo, Louvamos a Deus pela vida do Pr. Samuel de Souza por sua intrepidez e fé. Glória a Deus! Nosso estimado Pr. Samuel de Souza dedicou 46 de seus sessenta anos de ministério nesta boa igreja, que tanto amou, vindo ele a falecer no dia 31 de dezembro de 2010.</p>
            <p>A igreja continua avançando em sua marcha gloriosa. Inspirada na Palavra: <em>“De fé em fé... o justo viverá da fé”</em> <strong>(Romanos 1:17)</strong>. A PIB INGÁ prossegue escrevendo novos e belíssimos capítulos nesta História de Fé. Permanece nos propósitos para os quais foi organizada: a proclamação do evangelho de Cristo; o ensino da Palavra; o serviço cristão, a comunhão e a adoração ao Senhor da Igreja.</p>
            <p>Em 25 de março de 2012, a igreja deu posse como seu Pastor Sênior o Pr. Edimar Guimarães Pereira. Nesse novo tempo o Senhor também tem dado Graça e Unção para o nosso pastor conduzir esse rebanho. A igreja tem experimentado a alegria de ver as portas se abrirem em diversas áreas, especialmente no avanço missionário em nossa cidade. Com verdadeiro júbilo a Primeira Igreja Batista do Ingá pode dizer neste tempo de celebração do seu Jubileu de Ouro: <em>“Até aqui nos ajudou o Senhor”</em> <strong>1º Samuel 7:12</strong>.</p>
        </article>
    </section>
</x-guest-layout>
